config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'contents#index'

  resources :contents, only: [:index, :show]

  namespace :admin do
    resources :contents
    resources :users, only: [:show, :edit, :update]
    resource :accounts, only: [:edit, :update]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auth.rb
class Auth < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :content_categories
  has_many :contents, through: :content_categories
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user
  has_many :links, dependent: :destroy
  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  has_many :content_categories
  has_many :categories, through: :content_categories
  has_one_attached :thumbnail

  after_save :create_thumbnail

  validates :title, presence: true
  validates :description, presence: true

  def link_images
    links.map do |link|
      link_scraper = Scraper::NokogiriScraper.new(link.url)
      link_scraper.parse
      link_scraper.get_og_image
    end.reject(&:blank?)
  end

  private
  def create_thumbnail
    return if self.thumbnail.attached?
    image_urls = link_images

    image_url = image_urls.first
    tempfile = begin
                  open(image_url)
                rescue
                  nil
               end
    return if tempfile.blank? || !tempfile.is_a?(Tempfile)

    file_name = File.basename(URI.parse(image_url).path)
    file = File.open(tempfile)
    self.thumbnail.attach(io: file, filename: file_name)
  end
end

app/models/content_category.rb
class ContentCategory < ApplicationRecord
  belongs_to :content
  belongs_to :category
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
  has_many :auth
  has_many :contents

  enum gender: { male: 0, female: 1 , other: 2}, _prefix: true

  def full_name
    return email if !first_name? && !last_name?

    "#{last_name} #{first_name}"
  end

  class << self
    def find_or_create_for_auth!(auth)
      user = find_by(provider: auth.provider, uid: auth.uid)

      return user if user.present?

      password = Devise.friendly_token[0, 20]

      User.create!(
        provider: auth.provider,
        uid: auth.uid,
        email: auth.info.email || "#{SecureRandom.hex}@example.com",
        password: password,
        password_confirmation: password
      )
    end
  end

end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :authenticate_user!
  layout 'admin/application'
end

app/controllers/admin/contents_controller.rb
class Admin::ContentsController < Admin::ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  def index
    @contents = Content.all
  end

  def show
  end

  def new
    user = User.first
    @content = user.contents.new
  end

  def create
    user = User.first
    @content = user.contents.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to [:admin, @content], notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to [:admin, @content], notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to admin_contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_content
    @content = Content.find(params[:id])
  end

  def content_params
    params.require(:content).permit(:title, :description, :thumbnail, category_ids: [], links_attributes: [:name, :url, :_destroy, :id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

  def index
    @q = Content.ransack(params[:q])
    @contents = @q.result.includes(:categories).to_a.uniq
    @categories = Category.all
  end

  def show
    @content = Content.find(params[:id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def twitter
    @user = User.find_or_create_for_auth!(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/accounts/edit.html.erb
<%= form_with(model: @user, url: admin_accounts_path, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/contents/_form.html.erb
<%= form_with(model: [:admin, content], local: true) do |form| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
        <% content.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :thumbnail %>
    <%= form.file_field :thumbnail %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :categories %><br />
    <%= collection_check_boxes(:content, :category_ids, Category.all, :id, :name) do |b| %>
      <%= b.label { b.check_box + b.text } %>
    <% end %>
  </div>

  <div id="contents">
    <%= form.fields_for :links do |link| %>
      <%= render "link_fields", f: link %>
    <% end %>
    <div class="links">
      <%= link_to_add_association "リンク追加", form, :links %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/contents/_link_fields.html.erb
<div class="nested-fields form-inline">
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <%= link_to_remove_association "削除", f %>
</div>

app/views/admin/contents/edit.html.erb
<h1>Edit Content</h1>

<%= render 'form', content: @content %>

<%= link_to '戻る', admin_content_path(@content) %>

app/views/admin/contents/index.html.erb
<h2>コンテンツ一覧</h2>
<%= link_to '新規作成', new_admin_content_path %>
<ul>
  <% @contents.each do |content| %>
    <li>
      <%= link_to content.title, admin_content_path(content)  %>
      <ul>
        <li><%= content.description %></li>
      </ul>
    </li>
  <% end %>
</ul>

app/views/admin/contents/new.html.erb
<h1>Edit Medical Check</h1>

<%= render 'form', content: @content %>

<%= link_to '戻る', admin_contents_path %>

app/views/admin/contents/show.html.erb
<h2>コンテンツ</h2>
<%= link_to '編集', edit_admin_content_path(@content) %>
<%= link_to '削除', admin_content_path(@content), method: :delete %>
<h3><%= @content.title %></h3>
<p><%= @content.description %></p>

<h3>関連リンク</h3>
<ul>
  <% @content.links.each do |link| %>
    <li><%= link_to link.name, link.url, target: :blank %></li>
  <% end %>
</ul>

<%= link_to '戻る', admin_contents_path %>

app/views/admin/users/edit.html.erb
<%= form_with(model: [:admin, @user], local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :last_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.select :gender, User.genders.map {|k, v| [k, k] } %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_select(:birthday, prompt:"--",use_month_numbers:true, start_year:Time.now.year, end_year:1900, date_separator:'/') %>
  </div>

  <div class="field">
    <%= form.label :tel %>
    <%= form.text_field :tel %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/users/show.html.erb
<h2><%= @user.full_name %></h2>

<table>
  <thead>
    <tr>
      <th>氏名</th>
      <th>性別</th>
      <th>生年月日</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @user.full_name %></td>
      <td><%= @user.gender %></td>
      <td><%= @user.birthday&.strftime('%Y/%m/%d') %></td>
      <td><%= link_to '編集', edit_admin_user_path(@user) %></td>
      <td><%= link_to 'アカウント編集', edit_admin_accounts_path %></td>
    </tr>
  </tbody>
</table>

app/views/contents/index.html.erb
<h2>コンテンツ一覧</h2>

<%= search_form_for @q do |f| %>

  <%= f.label 'ワード' %>
  <%= f.search_field :title_or_description_cont %>

  <%= f.label 'カテゴリー' %>
  <%= f.collection_select :categories_id_eq, @categories, :id, :name, include_blank: '指定なし' %>

  <%= f.submit %>
<% end %>

<ul>
  <% @contents.each do |content| %>
    <li>
      <%= link_to content.title, content_path(content)  %>
      <ul>
        <% if content.thumbnail.attached? %>
          <li><%= image_tag content.thumbnail %></li>
        <% end %>
        <li><%= content.description %></li>
      </ul>
    </li>
  <% end %>
</ul>

app/views/contents/show.html.erb
<h2>コンテンツ</h2>

<h3><%= @content.title %></h3>
<p><%= @content.description %></p>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin | HimatsubushiManual</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <ul>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      <li><%= link_to 'ユーザー', admin_user_path(current_user) %></li>
      <li><%= link_to 'コンテンツ', admin_contents_path %></li>
    </ul>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HimatsubushiManual</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>